dist: bionic
language: python
python:
  - "3.10"

services:
  - docker

jobs:
  include:
    - stage: linting
      script:
        - pip install black==22.10.0 flake8==5.0.4
        - black . --check -S
        - flake8 .
