# Generated by Django 4.1.2 on 2022-10-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("socialaccount", "0003_extra_data_default_dict"),
        ("account", "0002_email_max_length"),
        ("accounts", "0002_rename_myuser_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="MyUser",
        ),
    ]
