# Generated by Django 4.1.2 on 2022-11-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="context",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="author",
            new_name="user",
        ),
    ]
