name: CI Pipeline

on: [push]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

      - name: Install Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: pip install black==22.10.0 flake8==5.0.4

      - name: Run black
        run: black . --check -S 
      
      - name: Run flake8
        run: flake8